import { addCollection } from '@iconify/react';
import materialIcons from '@iconify-json/material-icon-theme/icons.json';

// Register the Material Icon Theme set once at module load. Iconify keeps it
// in memory so all <Icon icon="material-icon-theme:..."/> calls render
// without a network fetch.
addCollection(materialIcons as Parameters<typeof addCollection>[0]);

// Map a filename to a Material Icon Theme icon key. Iconify renders these
// via the bundled material-icon-theme collection. Unknown files fall back
// to the generic "document" icon — still a real file glyph, just neutral.
export function iconNameForFile(name: string): string {
  const lower = name.toLowerCase();
  // Whole-filename specials beat extension rules.
  const fullMap: Record<string, string> = {
    'package.json': 'nodejs',
    'package-lock.json': 'nodejs',
    'yarn.lock': 'yarn',
    'pnpm-lock.yaml': 'pnpm',
    'tsconfig.json': 'tsconfig',
    'tsconfig.base.json': 'tsconfig',
    'vite.config.ts': 'vite',
    'vite.config.js': 'vite',
    'webpack.config.js': 'webpack',
    'rollup.config.js': 'rollup',
    'esbuild.config.js': 'esbuild',
    'babel.config.js': 'babel',
    '.babelrc': 'babel',
    '.eslintrc': 'eslint',
    '.eslintrc.js': 'eslint',
    '.eslintrc.json': 'eslint',
    '.prettierrc': 'prettier',
    '.prettierrc.json': 'prettier',
    dockerfile: 'docker',
    '.dockerignore': 'docker',
    'docker-compose.yml': 'docker',
    'docker-compose.yaml': 'docker',
    makefile: 'makefile',
    '.gitignore': 'git',
    '.gitattributes': 'git',
    '.gitmodules': 'git',
    '.editorconfig': 'editorconfig',
    '.npmrc': 'npm',
    '.nvmrc': 'nodejs',
    'readme.md': 'readme',
    license: 'certificate',
    'license.md': 'certificate',
    'cargo.toml': 'rust',
    'cargo.lock': 'rust',
    'go.mod': 'go',
    'go.sum': 'go',
    gemfile: 'ruby',
    'gemfile.lock': 'ruby',
    'pyproject.toml': 'python',
    'requirements.txt': 'python',
    pipfile: 'python',
    'pipfile.lock': 'python',
  };
  if (fullMap[lower]) return `material-icon-theme:${fullMap[lower]}`;

  // Match `.env`, `.env.local`, `.env.production`, etc.
  if (lower === '.env' || lower.startsWith('.env.')) return 'material-icon-theme:tune';

  const ext = lower.includes('.') ? lower.slice(lower.lastIndexOf('.') + 1) : '';
  const extMap: Record<string, string> = {
    ts: 'typescript',
    tsx: 'react-ts',
    js: 'javascript',
    mjs: 'javascript',
    cjs: 'javascript',
    jsx: 'react',
    json: 'json',
    jsonl: 'json',
    json5: 'json', // jsonl/json5 fall back to json
    yaml: 'yaml',
    yml: 'yaml',
    toml: 'settings',
    ini: 'settings',
    md: 'markdown',
    markdown: 'markdown',
    mdx: 'mdx',
    py: 'python',
    pyc: 'python',
    pyi: 'python',
    ipynb: 'jupyter',
    rb: 'ruby',
    erb: 'ruby',
    go: 'go',
    rs: 'rust',
    java: 'java',
    kt: 'kotlin',
    kts: 'kotlin',
    scala: 'scala',
    swift: 'swift',
    cs: 'csharp',
    fs: 'fsharp',
    fsi: 'fsharp',
    c: 'c',
    h: 'h',
    cpp: 'cpp',
    cc: 'cpp',
    cxx: 'cpp',
    hpp: 'hpp',
    php: 'php',
    blade: 'php',
    lua: 'lua',
    dart: 'dart',
    vue: 'vue',
    svelte: 'svelte',
    elm: 'elm',
    ex: 'elixir',
    exs: 'elixir',
    erl: 'erlang',
    hrl: 'erlang',
    r: 'r',
    sql: 'database',
    graphql: 'graphql',
    gql: 'graphql',
    html: 'html',
    htm: 'html',
    xml: 'xml',
    svg: 'svg',
    css: 'css',
    scss: 'sass',
    sass: 'sass',
    less: 'less',
    postcss: 'postcss',
    sh: 'console',
    bash: 'console',
    zsh: 'console',
    fish: 'console',
    ps1: 'powershell',
    csv: 'table',
    tsv: 'table',
    xlsx: 'table',
    xls: 'table',
    png: 'image',
    jpg: 'image',
    jpeg: 'image',
    gif: 'image',
    webp: 'image',
    ico: 'image',
    avif: 'image',
    bmp: 'image',
    mp3: 'audio',
    wav: 'audio',
    flac: 'audio',
    ogg: 'audio',
    mp4: 'video',
    mov: 'video',
    webm: 'video',
    mkv: 'video',
    pdf: 'pdf',
    zip: 'zip',
    tar: 'zip',
    gz: 'zip',
    bz2: 'zip',
    '7z': 'zip',
    rar: 'zip',
    dmg: 'zip',
    woff: 'font',
    woff2: 'font',
    ttf: 'font',
    otf: 'font',
    eot: 'font',
    txt: 'document',
    log: 'log',
  };
  if (extMap[ext]) return `material-icon-theme:${extMap[ext]}`;
  return 'material-icon-theme:document';
}
